"""Added artist tables


Revision ID: 01803a5cba32
Revises: f50103711c90
Create Date: 2024-03-05 15:14:42.781065

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '01803a5cba32'
down_revision = 'f50103711c90'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('all_time_artists',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_stats_id', sa.Integer(), nullable=False),
    sa.Column('artist', sa.String(length=100), nullable=True),
    sa.ForeignKeyConstraint(['user_stats_id'], ['user_stats.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('recent_artists',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_stats_id', sa.Integer(), nullable=False),
    sa.Column('artist', sa.String(length=100), nullable=True),
    sa.ForeignKeyConstraint(['user_stats_id'], ['user_stats.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('recent_artists')
    op.drop_table('all_time_artists')
    # ### end Alembic commands ###
