"""Added user stats and genre tables

Revision ID: 0951d9d24938
Revises: 4b4a44641ccd
Create Date: 2024-03-04 16:09:31.254360

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0951d9d24938'
down_revision = '4b4a44641ccd'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user_stats',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('all_time_genres',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('genre', sa.String(length=100), nullable=True),
    sa.Column('genre_count', sa.Integer(), nullable=True),
    sa.Column('user_stats_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['user_stats_id'], ['user_stats.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('recent_genres',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('genre', sa.String(length=100), nullable=True),
    sa.Column('genre_count', sa.Integer(), nullable=True),
    sa.Column('user_stats_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['user_stats_id'], ['user_stats.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('most_recent_login', sa.DateTime(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_column('most_recent_login')

    op.drop_table('recent_genres')
    op.drop_table('all_time_genres')
    op.drop_table('user_stats')
    # ### end Alembic commands ###
