"""name changes part 2

Revision ID: 3381a0211b3c
Revises: 4d21c197e655
Create Date: 2024-03-12 23:47:43.791455

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '3381a0211b3c'
down_revision = '4d21c197e655'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('all_time_tracks',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_stats_id', sa.Integer(), nullable=False),
    sa.Column('song', sa.String(length=100), nullable=True),
    sa.ForeignKeyConstraint(['user_stats_id'], ['user_stats.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('recent_tracks',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_stats_id', sa.Integer(), nullable=False),
    sa.Column('song', sa.String(length=100), nullable=True),
    sa.ForeignKeyConstraint(['user_stats_id'], ['user_stats.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_table('all_time_songs')
    op.drop_table('recent_songs')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('recent_songs',
    sa.Column('id', mysql.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('user_stats_id', mysql.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('song', mysql.VARCHAR(length=100), nullable=True),
    sa.ForeignKeyConstraint(['user_stats_id'], ['user_stats.id'], name='recent_songs_ibfk_1', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_table('all_time_songs',
    sa.Column('id', mysql.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('user_stats_id', mysql.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('song', mysql.VARCHAR(length=100), nullable=True),
    sa.ForeignKeyConstraint(['user_stats_id'], ['user_stats.id'], name='all_time_songs_ibfk_1', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.drop_table('recent_tracks')
    op.drop_table('all_time_tracks')
    # ### end Alembic commands ###
