"""altered matches configuration

Revision ID: 8640ffeb6ba2
Revises: 9ed43589b678
Create Date: 2024-04-12 12:21:16.680047

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '8640ffeb6ba2'
down_revision = '9ed43589b678'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('matches', schema=None) as batch_op:
        batch_op.add_column(sa.Column('user_1_id', sa.Integer(), nullable=False))
        batch_op.add_column(sa.Column('user_2_id', sa.Integer(), nullable=False))
        batch_op.drop_constraint('matches_ibfk_2', type_='foreignkey')
        batch_op.drop_constraint('matches_ibfk_1', type_='foreignkey')
        batch_op.create_foreign_key(None, 'user', ['user_2_id'], ['id'], ondelete='CASCADE')
        batch_op.create_foreign_key(None, 'user', ['user_1_id'], ['id'], ondelete='CASCADE')
        batch_op.drop_column('second_user_id')
        batch_op.drop_column('first_user_id')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('matches', schema=None) as batch_op:
        batch_op.add_column(sa.Column('first_user_id', mysql.INTEGER(), autoincrement=False, nullable=False))
        batch_op.add_column(sa.Column('second_user_id', mysql.INTEGER(), autoincrement=False, nullable=False))
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key('matches_ibfk_1', 'user', ['first_user_id'], ['id'], ondelete='CASCADE')
        batch_op.create_foreign_key('matches_ibfk_2', 'user', ['second_user_id'], ['id'], ondelete='CASCADE')
        batch_op.drop_column('user_2_id')
        batch_op.drop_column('user_1_id')

    # ### end Alembic commands ###
