"""empty message

Revision ID: 8d46a831f91d
Revises: a4f4d121194f
Create Date: 2024-03-29 22:51:05.944710

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '8d46a831f91d'
down_revision = 'a4f4d121194f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('all_time_tracks', schema=None) as batch_op:
        batch_op.alter_column('preview_url',
               existing_type=mysql.VARCHAR(length=100),
               type_=sa.String(length=200),
               existing_nullable=True)

    with op.batch_alter_table('medium_tracks', schema=None) as batch_op:
        batch_op.alter_column('preview_url',
               existing_type=mysql.VARCHAR(length=100),
               type_=sa.String(length=200),
               existing_nullable=True)

    with op.batch_alter_table('recent_tracks', schema=None) as batch_op:
        batch_op.alter_column('preview_url',
               existing_type=mysql.VARCHAR(length=100),
               type_=sa.String(length=200),
               existing_nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('recent_tracks', schema=None) as batch_op:
        batch_op.alter_column('preview_url',
               existing_type=sa.String(length=200),
               type_=mysql.VARCHAR(length=100),
               existing_nullable=True)

    with op.batch_alter_table('medium_tracks', schema=None) as batch_op:
        batch_op.alter_column('preview_url',
               existing_type=sa.String(length=200),
               type_=mysql.VARCHAR(length=100),
               existing_nullable=True)

    with op.batch_alter_table('all_time_tracks', schema=None) as batch_op:
        batch_op.alter_column('preview_url',
               existing_type=sa.String(length=200),
               type_=mysql.VARCHAR(length=100),
               existing_nullable=True)

    # ### end Alembic commands ###
