"""added 6 month user data

Revision ID: 9a83cc3b5619
Revises: a499c43bd21c
Create Date: 2024-03-29 16:02:59.455075

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9a83cc3b5619'
down_revision = 'a499c43bd21c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('medium_artists',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_stats_id', sa.Integer(), nullable=False),
    sa.Column('artist', sa.String(length=100), nullable=True),
    sa.ForeignKeyConstraint(['user_stats_id'], ['user_stats.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('medium_genres',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_stats_id', sa.Integer(), nullable=False),
    sa.Column('genre', sa.String(length=100), nullable=True),
    sa.Column('genre_count', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['user_stats_id'], ['user_stats.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('medium_tracks',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_stats_id', sa.Integer(), nullable=False),
    sa.Column('song', sa.String(length=100), nullable=True),
    sa.ForeignKeyConstraint(['user_stats_id'], ['user_stats.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('user_stats', schema=None) as batch_op:
        batch_op.add_column(sa.Column('popularity_m', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('tempo_m', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('loudness_m', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('acousticness_m', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('danceability_m', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('valence_m', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('energy_m', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('speechiness_m', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('variance_m', sa.Float(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user_stats', schema=None) as batch_op:
        batch_op.drop_column('variance_m')
        batch_op.drop_column('speechiness_m')
        batch_op.drop_column('energy_m')
        batch_op.drop_column('valence_m')
        batch_op.drop_column('danceability_m')
        batch_op.drop_column('acousticness_m')
        batch_op.drop_column('loudness_m')
        batch_op.drop_column('tempo_m')
        batch_op.drop_column('popularity_m')

    op.drop_table('medium_tracks')
    op.drop_table('medium_genres')
    op.drop_table('medium_artists')
    # ### end Alembic commands ###
