"""added Matches table

Revision ID: 9ed43589b678
Revises: 1f7a993e768a
Create Date: 2024-04-11 22:59:33.984526

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9ed43589b678'
down_revision = '1f7a993e768a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('matches',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('first_user_id', sa.Integer(), nullable=False),
    sa.Column('second_user_id', sa.Integer(), nullable=False),
    sa.Column('compatibility_score', sa.Float(), nullable=True),
    sa.ForeignKeyConstraint(['first_user_id'], ['user.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['second_user_id'], ['user.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('matches')
    # ### end Alembic commands ###
