"""increased capacity for artist column across multiple tables

Revision ID: a9167235d3a6
Revises: bb7fb06cb4fd
Create Date: 2024-04-19 00:17:38.688185

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'a9167235d3a6'
down_revision = 'bb7fb06cb4fd'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('all_time_artists', schema=None) as batch_op:
        batch_op.alter_column('artist',
               existing_type=mysql.VARCHAR(length=100),
               type_=sa.String(length=10000),
               existing_nullable=True)
        batch_op.alter_column('img_url',
               existing_type=mysql.VARCHAR(length=100),
               type_=sa.String(length=256),
               existing_nullable=True)
        batch_op.alter_column('spotify_url',
               existing_type=mysql.VARCHAR(length=100),
               type_=sa.String(length=256),
               existing_nullable=True)
        batch_op.alter_column('href',
               existing_type=mysql.VARCHAR(length=100),
               type_=sa.String(length=256),
               existing_nullable=True)

    with op.batch_alter_table('all_time_genres', schema=None) as batch_op:
        batch_op.alter_column('genre',
               existing_type=mysql.VARCHAR(length=100),
               type_=sa.String(length=256),
               existing_nullable=True)

    with op.batch_alter_table('all_time_tracks', schema=None) as batch_op:
        batch_op.alter_column('song',
               existing_type=mysql.VARCHAR(length=100),
               type_=sa.String(length=256),
               existing_nullable=True)
        batch_op.alter_column('artist',
               existing_type=mysql.VARCHAR(length=100),
               type_=sa.String(length=10000),
               existing_nullable=True)
        batch_op.alter_column('track_id',
               existing_type=mysql.VARCHAR(length=100),
               type_=sa.String(length=256),
               existing_nullable=True)
        batch_op.alter_column('album_art_img_url',
               existing_type=mysql.VARCHAR(length=100),
               type_=sa.String(length=256),
               existing_nullable=True)
        batch_op.alter_column('spotify_url',
               existing_type=mysql.VARCHAR(length=100),
               type_=sa.String(length=256),
               existing_nullable=True)
        batch_op.alter_column('href',
               existing_type=mysql.VARCHAR(length=100),
               type_=sa.String(length=256),
               existing_nullable=True)

    with op.batch_alter_table('medium_artists', schema=None) as batch_op:
        batch_op.alter_column('artist',
               existing_type=mysql.VARCHAR(length=100),
               type_=sa.String(length=10000),
               existing_nullable=True)
        batch_op.alter_column('img_url',
               existing_type=mysql.VARCHAR(length=100),
               type_=sa.String(length=256),
               existing_nullable=True)
        batch_op.alter_column('spotify_url',
               existing_type=mysql.VARCHAR(length=100),
               type_=sa.String(length=256),
               existing_nullable=True)
        batch_op.alter_column('href',
               existing_type=mysql.VARCHAR(length=100),
               type_=sa.String(length=256),
               existing_nullable=True)

    with op.batch_alter_table('medium_genres', schema=None) as batch_op:
        batch_op.alter_column('genre',
               existing_type=mysql.VARCHAR(length=100),
               type_=sa.String(length=256),
               existing_nullable=True)

    with op.batch_alter_table('medium_tracks', schema=None) as batch_op:
        batch_op.alter_column('song',
               existing_type=mysql.VARCHAR(length=100),
               type_=sa.String(length=256),
               existing_nullable=True)
        batch_op.alter_column('artist',
               existing_type=mysql.VARCHAR(length=100),
               type_=sa.String(length=10000),
               existing_nullable=True)
        batch_op.alter_column('track_id',
               existing_type=mysql.VARCHAR(length=100),
               type_=sa.String(length=256),
               existing_nullable=True)
        batch_op.alter_column('album_art_img_url',
               existing_type=mysql.VARCHAR(length=100),
               type_=sa.String(length=256),
               existing_nullable=True)
        batch_op.alter_column('spotify_url',
               existing_type=mysql.VARCHAR(length=100),
               type_=sa.String(length=256),
               existing_nullable=True)
        batch_op.alter_column('href',
               existing_type=mysql.VARCHAR(length=100),
               type_=sa.String(length=256),
               existing_nullable=True)

    with op.batch_alter_table('recent_artists', schema=None) as batch_op:
        batch_op.alter_column('artist',
               existing_type=mysql.VARCHAR(length=100),
               type_=sa.String(length=10000),
               existing_nullable=True)
        batch_op.alter_column('img_url',
               existing_type=mysql.VARCHAR(length=100),
               type_=sa.String(length=256),
               existing_nullable=True)
        batch_op.alter_column('spotify_url',
               existing_type=mysql.VARCHAR(length=100),
               type_=sa.String(length=256),
               existing_nullable=True)
        batch_op.alter_column('href',
               existing_type=mysql.VARCHAR(length=100),
               type_=sa.String(length=256),
               existing_nullable=True)

    with op.batch_alter_table('recent_genres', schema=None) as batch_op:
        batch_op.alter_column('genre',
               existing_type=mysql.VARCHAR(length=100),
               type_=sa.String(length=256),
               existing_nullable=True)

    with op.batch_alter_table('recent_tracks', schema=None) as batch_op:
        batch_op.alter_column('song',
               existing_type=mysql.VARCHAR(length=100),
               type_=sa.String(length=256),
               existing_nullable=True)
        batch_op.alter_column('artist',
               existing_type=mysql.VARCHAR(length=100),
               type_=sa.String(length=10000),
               existing_nullable=True)
        batch_op.alter_column('track_id',
               existing_type=mysql.VARCHAR(length=100),
               type_=sa.String(length=256),
               existing_nullable=True)
        batch_op.alter_column('album_art_img_url',
               existing_type=mysql.VARCHAR(length=100),
               type_=sa.String(length=256),
               existing_nullable=True)
        batch_op.alter_column('spotify_url',
               existing_type=mysql.VARCHAR(length=100),
               type_=sa.String(length=256),
               existing_nullable=True)
        batch_op.alter_column('href',
               existing_type=mysql.VARCHAR(length=100),
               type_=sa.String(length=256),
               existing_nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('recent_tracks', schema=None) as batch_op:
        batch_op.alter_column('href',
               existing_type=sa.String(length=256),
               type_=mysql.VARCHAR(length=100),
               existing_nullable=True)
        batch_op.alter_column('spotify_url',
               existing_type=sa.String(length=256),
               type_=mysql.VARCHAR(length=100),
               existing_nullable=True)
        batch_op.alter_column('album_art_img_url',
               existing_type=sa.String(length=256),
               type_=mysql.VARCHAR(length=100),
               existing_nullable=True)
        batch_op.alter_column('track_id',
               existing_type=sa.String(length=256),
               type_=mysql.VARCHAR(length=100),
               existing_nullable=True)
        batch_op.alter_column('artist',
               existing_type=sa.String(length=10000),
               type_=mysql.VARCHAR(length=100),
               existing_nullable=True)
        batch_op.alter_column('song',
               existing_type=sa.String(length=256),
               type_=mysql.VARCHAR(length=100),
               existing_nullable=True)

    with op.batch_alter_table('recent_genres', schema=None) as batch_op:
        batch_op.alter_column('genre',
               existing_type=sa.String(length=256),
               type_=mysql.VARCHAR(length=100),
               existing_nullable=True)

    with op.batch_alter_table('recent_artists', schema=None) as batch_op:
        batch_op.alter_column('href',
               existing_type=sa.String(length=256),
               type_=mysql.VARCHAR(length=100),
               existing_nullable=True)
        batch_op.alter_column('spotify_url',
               existing_type=sa.String(length=256),
               type_=mysql.VARCHAR(length=100),
               existing_nullable=True)
        batch_op.alter_column('img_url',
               existing_type=sa.String(length=256),
               type_=mysql.VARCHAR(length=100),
               existing_nullable=True)
        batch_op.alter_column('artist',
               existing_type=sa.String(length=10000),
               type_=mysql.VARCHAR(length=100),
               existing_nullable=True)

    with op.batch_alter_table('medium_tracks', schema=None) as batch_op:
        batch_op.alter_column('href',
               existing_type=sa.String(length=256),
               type_=mysql.VARCHAR(length=100),
               existing_nullable=True)
        batch_op.alter_column('spotify_url',
               existing_type=sa.String(length=256),
               type_=mysql.VARCHAR(length=100),
               existing_nullable=True)
        batch_op.alter_column('album_art_img_url',
               existing_type=sa.String(length=256),
               type_=mysql.VARCHAR(length=100),
               existing_nullable=True)
        batch_op.alter_column('track_id',
               existing_type=sa.String(length=256),
               type_=mysql.VARCHAR(length=100),
               existing_nullable=True)
        batch_op.alter_column('artist',
               existing_type=sa.String(length=10000),
               type_=mysql.VARCHAR(length=100),
               existing_nullable=True)
        batch_op.alter_column('song',
               existing_type=sa.String(length=256),
               type_=mysql.VARCHAR(length=100),
               existing_nullable=True)

    with op.batch_alter_table('medium_genres', schema=None) as batch_op:
        batch_op.alter_column('genre',
               existing_type=sa.String(length=256),
               type_=mysql.VARCHAR(length=100),
               existing_nullable=True)

    with op.batch_alter_table('medium_artists', schema=None) as batch_op:
        batch_op.alter_column('href',
               existing_type=sa.String(length=256),
               type_=mysql.VARCHAR(length=100),
               existing_nullable=True)
        batch_op.alter_column('spotify_url',
               existing_type=sa.String(length=256),
               type_=mysql.VARCHAR(length=100),
               existing_nullable=True)
        batch_op.alter_column('img_url',
               existing_type=sa.String(length=256),
               type_=mysql.VARCHAR(length=100),
               existing_nullable=True)
        batch_op.alter_column('artist',
               existing_type=sa.String(length=10000),
               type_=mysql.VARCHAR(length=100),
               existing_nullable=True)

    with op.batch_alter_table('all_time_tracks', schema=None) as batch_op:
        batch_op.alter_column('href',
               existing_type=sa.String(length=256),
               type_=mysql.VARCHAR(length=100),
               existing_nullable=True)
        batch_op.alter_column('spotify_url',
               existing_type=sa.String(length=256),
               type_=mysql.VARCHAR(length=100),
               existing_nullable=True)
        batch_op.alter_column('album_art_img_url',
               existing_type=sa.String(length=256),
               type_=mysql.VARCHAR(length=100),
               existing_nullable=True)
        batch_op.alter_column('track_id',
               existing_type=sa.String(length=256),
               type_=mysql.VARCHAR(length=100),
               existing_nullable=True)
        batch_op.alter_column('artist',
               existing_type=sa.String(length=10000),
               type_=mysql.VARCHAR(length=100),
               existing_nullable=True)
        batch_op.alter_column('song',
               existing_type=sa.String(length=256),
               type_=mysql.VARCHAR(length=100),
               existing_nullable=True)

    with op.batch_alter_table('all_time_genres', schema=None) as batch_op:
        batch_op.alter_column('genre',
               existing_type=sa.String(length=256),
               type_=mysql.VARCHAR(length=100),
               existing_nullable=True)

    with op.batch_alter_table('all_time_artists', schema=None) as batch_op:
        batch_op.alter_column('href',
               existing_type=sa.String(length=256),
               type_=mysql.VARCHAR(length=100),
               existing_nullable=True)
        batch_op.alter_column('spotify_url',
               existing_type=sa.String(length=256),
               type_=mysql.VARCHAR(length=100),
               existing_nullable=True)
        batch_op.alter_column('img_url',
               existing_type=sa.String(length=256),
               type_=mysql.VARCHAR(length=100),
               existing_nullable=True)
        batch_op.alter_column('artist',
               existing_type=sa.String(length=10000),
               type_=mysql.VARCHAR(length=100),
               existing_nullable=True)

    # ### end Alembic commands ###
