"""delete settings update

Revision ID: ec25e9191bc4
Revises: 01803a5cba32
Create Date: 2024-03-09 15:34:07.019758

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ec25e9191bc4'
down_revision = '01803a5cba32'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('all_time_artists', schema=None) as batch_op:
        batch_op.drop_constraint('all_time_artists_ibfk_1', type_='foreignkey')
        batch_op.create_foreign_key(None, 'user_stats', ['user_stats_id'], ['id'], ondelete='CASCADE')

    with op.batch_alter_table('all_time_genres', schema=None) as batch_op:
        batch_op.drop_constraint('all_time_genres_ibfk_1', type_='foreignkey')
        batch_op.create_foreign_key(None, 'user_stats', ['user_stats_id'], ['id'], ondelete='CASCADE')

    with op.batch_alter_table('recent_artists', schema=None) as batch_op:
        batch_op.drop_constraint('recent_artists_ibfk_1', type_='foreignkey')
        batch_op.create_foreign_key(None, 'user_stats', ['user_stats_id'], ['id'], ondelete='CASCADE')

    with op.batch_alter_table('recent_genres', schema=None) as batch_op:
        batch_op.drop_constraint('recent_genres_ibfk_1', type_='foreignkey')
        batch_op.create_foreign_key(None, 'user_stats', ['user_stats_id'], ['id'], ondelete='CASCADE')

    with op.batch_alter_table('user_stats', schema=None) as batch_op:
        batch_op.drop_constraint('user_stats_ibfk_1', type_='foreignkey')
        batch_op.create_foreign_key(None, 'user', ['user_id'], ['id'], ondelete='CASCADE')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user_stats', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key('user_stats_ibfk_1', 'user', ['user_id'], ['id'])

    with op.batch_alter_table('recent_genres', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key('recent_genres_ibfk_1', 'user_stats', ['user_stats_id'], ['id'])

    with op.batch_alter_table('recent_artists', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key('recent_artists_ibfk_1', 'user_stats', ['user_stats_id'], ['id'])

    with op.batch_alter_table('all_time_genres', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key('all_time_genres_ibfk_1', 'user_stats', ['user_stats_id'], ['id'])

    with op.batch_alter_table('all_time_artists', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key('all_time_artists_ibfk_1', 'user_stats', ['user_stats_id'], ['id'])

    # ### end Alembic commands ###
