"""Add cascade delete rules and new user stats

Revision ID: f50103711c90
Revises: 0951d9d24938
Create Date: 2024-03-05 13:51:04.491722

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f50103711c90'
down_revision = '0951d9d24938'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user_stats', schema=None) as batch_op:
        batch_op.add_column(sa.Column('popularity_r', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('popularity_a', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('tempo_r', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('tempo_a', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('loudness_r', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('loudness_a', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('acousticness_r', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('acousticness_a', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('danceability_r', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('danceability_a', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('valence_r', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('valence_a', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('energy_r', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('energy_a', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('speechiness_r', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('speechiness_a', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('variance_r', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('variance_a', sa.Float(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user_stats', schema=None) as batch_op:
        batch_op.drop_column('variance_a')
        batch_op.drop_column('variance_r')
        batch_op.drop_column('speechiness_a')
        batch_op.drop_column('speechiness_r')
        batch_op.drop_column('energy_a')
        batch_op.drop_column('energy_r')
        batch_op.drop_column('valence_a')
        batch_op.drop_column('valence_r')
        batch_op.drop_column('danceability_a')
        batch_op.drop_column('danceability_r')
        batch_op.drop_column('acousticness_a')
        batch_op.drop_column('acousticness_r')
        batch_op.drop_column('loudness_a')
        batch_op.drop_column('loudness_r')
        batch_op.drop_column('tempo_a')
        batch_op.drop_column('tempo_r')
        batch_op.drop_column('popularity_a')
        batch_op.drop_column('popularity_r')

    # ### end Alembic commands ###
